[build]
  publish = "."

[[redirects]]
  from = "/todos"
  to = "/todos.html"
  status = 200

[[redirects]]
  from = "/notes"
  to = "/notes.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/sleep-tracker.html"
  status = 200
